# Generated by Django 4.1 on 2025-12-08 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('entyear', models.IntegerField()),
                ('stdNo', models.CharField(max_length=8, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name1', models.CharField(max_length=255)),
                ('name2', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=1)),
                ('COO', models.CharField(max_length=50)),
                ('enrolled', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'student',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectNo', models.CharField(max_length=20)),
                ('version', models.CharField(default='A', max_length=5)),
                ('title', models.CharField(max_length=100)),
                ('fsyear', models.IntegerField()),
                ('term', models.IntegerField()),
                ('target_year', models.IntegerField()),
                ('adjust_comment', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_code', models.CharField(max_length=20)),
                ('text', models.TextField(blank=True)),
                ('points', models.IntegerField()),
                ('gyo', models.IntegerField()),
                ('retu', models.IntegerField()),
                ('answer', models.CharField(max_length=255)),
                ('width', models.IntegerField(default=1)),
                ('height', models.IntegerField(default=60)),
                ('bunrui', models.CharField(blank=True, max_length=30)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.exam')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TF', models.BooleanField(default=False)),
                ('hosei', models.IntegerField(default=0)),
                ('ten', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentExamVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectNo', models.CharField(max_length=20)),
                ('fsyear', models.IntegerField()),
                ('term', models.IntegerField()),
                ('version', models.CharField(max_length=5)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.student')),
            ],
            options={
                'unique_together': {('student', 'subjectNo', 'fsyear', 'term')},
            },
        ),
    ]
