# Generated by Django 4.1 on 2025-12-08 22:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0002_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='subjectNo',
        ),
        migrations.AddField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exam2.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='adjust_comment',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fsyear',
            field=models.CharField(default='2024', max_length=4),
        ),
        migrations.AlterField(
            model_name='exam',
            name='target_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
