# Generated by Django 4.1 on 2025-12-08 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0004_rename_q_code_question_question_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('term', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='exam2.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_versions', to='exam2.subject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'year', 'term')},
            },
        ),
        migrations.CreateModel(
            name='StudentExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TF', models.IntegerField(default=0)),
                ('hosei', models.IntegerField(default=0)),
                ('ten', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam2.exam')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_answers', to='exam2.question')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exam2.student')),
            ],
            options={
                'unique_together': {('student', 'exam', 'question')},
            },
        ),
    ]
