# Generated by Django 4.1 on 2025-12-09 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0005_studentversion_studentexam'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentversion',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='studentversion',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentversion',
            name='subject',
        ),
        migrations.DeleteModel(
            name='StudentAnswer',
        ),
        migrations.DeleteModel(
            name='StudentVersion',
        ),
    ]
