# Generated by Django 4.1 on 2025-12-10 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0006_alter_studentversion_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='question',
            name='bunrui',
        ),
        migrations.RemoveField(
            model_name='question',
            name='gyo',
        ),
        migrations.RemoveField(
            model_name='question',
            name='height',
        ),
        migrations.RemoveField(
            model_name='question',
            name='points',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_no',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_code',
        ),
        migrations.RemoveField(
            model_name='question',
            name='retu',
        ),
        migrations.RemoveField(
            model_name='question',
            name='width',
        ),
        migrations.AddField(
            model_name='exam',
            name='answer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='exam',
            name='bunrui',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='gyo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='exam',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='q_no',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='question_code',
            field=models.CharField(default='TEMP', max_length=20),
        ),
        migrations.AddField(
            model_name='exam',
            name='retu',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='width',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='ExamAdjust',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjust', models.IntegerField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.exam')),
                ('stdNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.student')),
            ],
            options={
                'unique_together': {('exam', 'stdNo')},
            },
        ),
    ]
