# Generated by Django 4.1 on 2025-12-10 10:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0007_remove_question_answer_remove_question_bunrui_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['subject__subjectNo', 'fsyear', 'term', 'version']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['gyo', 'retu']},
        ),
        migrations.RenameField(
            model_name='examadjust',
            old_name='stdNo',
            new_name='student',
        ),
        migrations.RenameField(
            model_name='subject',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='ten',
        ),
        migrations.RemoveField(
            model_name='studentexam',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='description',
        ),
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='question',
            name='bunrui',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='question',
            name='gyo',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='height',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='q_no',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='question',
            name='retu',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='width',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='exam',
            name='adjust_comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='fsyear',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam2.subject'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='term',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='exam',
            name='version',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.exam'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.question'),
        ),
        migrations.AlterField(
            model_name='studentexam',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.student'),
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together={('subject', 'fsyear', 'term', 'version')},
        ),
        migrations.AlterUniqueTogether(
            name='examadjust',
            unique_together={('exam', 'student')},
        ),
        migrations.RemoveField(
            model_name='exam',
            name='answer',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='bunrui',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='gyo',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='height',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='points',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='q_no',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='question_code',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='retu',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='target_year',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='width',
        ),
    ]
