# Generated by Django 4.1 on 2025-12-11 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0008_alter_exam_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamversion',
            name='subject',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam2.subject'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentexamversion',
            unique_together={('student', 'subject', 'fsyear', 'term')},
        ),
        migrations.RemoveField(
            model_name='studentexamversion',
            name='subjectNo',
        ),
    ]
