# Generated by Django 4.1 on 2025-12-11 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0009_alter_studentexamversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='studentexamversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='studentexamversion',
            name='exam',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='exam2.exam'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='studentexamversion',
            unique_together={('student', 'exam')},
        ),
        migrations.RemoveField(
            model_name='studentexamversion',
            name='fsyear',
        ),
        migrations.RemoveField(
            model_name='studentexamversion',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='studentexamversion',
            name='term',
        ),
        migrations.RemoveField(
            model_name='studentexamversion',
            name='version',
        ),
    ]
