# Generated by Django 4.1 on 2025-12-11 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0010_alter_studentexamversion_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='nenji',
            field=models.IntegerField(default=1),
        ),
    ]
