# Generated by Django 4.1 on 2025-12-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0011_subject_nenji'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='problem_hash',
            field=models.CharField(blank=True, db_index=True, help_text='問題内容を一意に識別するハッシュ（answers_xxxx.json の metainfo.hash）', max_length=32, null=True),
        ),
    ]
