# Generated by Django 4.1 on 2025-12-16 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0012_exam_problem_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='fsyear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='term',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectNo',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='subject',
            index=models.Index(fields=['subjectNo', 'fsyear'], name='exam2_subje_subject_ef9ed5_idx'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('subjectNo', 'fsyear'), name='uq_subject_subjectNo_fsyear'),
        ),
    ]
