# Generated by Django 4.1 on 2025-12-16 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0013_subject_fsyear_subject_term_alter_subject_subjectno_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['subject__subjectNo', 'subject__fsyear', 'subject__term', 'version']},
        ),
        migrations.AlterUniqueTogether(
            name='exam',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam2.subject'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='fsyear',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(fields=('subject', 'version'), name='uq_exam_subject_version'),
        ),
        migrations.RemoveField(
            model_name='exam',
            name='fsyear',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='term',
        ),
    ]
