# Generated by Django 4.1 on 2025-12-17 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam2', '0014_alter_exam_options_alter_exam_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='fsyear',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='term',
            field=models.IntegerField(),
        ),
    ]
